name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Default permissions are read-only
permissions: read-all

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read   # REQUIRED for checkout
      actions: write  # REQUIRED for cache-to: type=gha
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: wordpress-gmail-cli:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Make scripts executable
        run: chmod +x bin/*.sh

      - name: Test Docker image
        run: bin/test-docker.sh

      - name: Test shell scripts
        run: bin/test-scripts.sh

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-and-test] # Ensure build job passes before releasing
    permissions:
      contents: write   # REQUIRED to create release/tag
      packages: write  # REQUIRED to push packages (Docker image to GHCR)
    # Run only on push to main with specific commit message
    if: >
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main' &&
      contains(github.event.head_commit.message, 'chore: release v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for release notes generation / tag info

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from commit message
        id: version
        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          # Extract version X.Y.Z from commit message like "chore: release vX.Y.Z ..."
          if [[ "$COMMIT_MESSAGE" =~ chore:\ release\ v([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            VERSION="${BASH_REMATCH[1]}"
            # Basic validation
            if [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "Extracted version: $VERSION"
              echo "version=$VERSION" >> $GITHUB_OUTPUT
            else
              echo "Error: Invalid version format extracted: $VERSION" >&2
              exit 1
            fi
          else
            echo "Error: Commit message does not contain 'chore: release vX.Y.Z'." >&2
            echo "Commit message was: $COMMIT_MESSAGE" >&2
            exit 1 # Fail if version not found

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }}
          # Use repository name which includes owner: owner/repo
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1 # Or pin to specific v1.x.y
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: Release v${{ steps.version.outputs.version }}
          generate_release_notes: true # Auto-generate release notes from commits
          # Verify these file paths are correct relative to repo root
          files: |
            bin/wordpress-gmail-cli.sh
            wp-social-auth.php
            bin/enhance-ssl-security.sh
