name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.txt'
      - 'LICENSE'
      - '.github/ISSUE_TEMPLATE/**'
      - '.gitignore'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Default permissions are read-only
permissions: read-all

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # For PR comments
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, zip, intl, json, curl
          tools: phpcs, phpstan, php-cs-fixer
          coverage: none

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: error
          
      - name: Run shfmt
        uses: luizm/action-sh-checker@v0.5.0
        env:
          SHFMT_OPTS: -i 2 -ci -bn
        with:
          sh_checker_comment: true
          sh_checker_exclude: vendor

      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs --standard=PSR12 wp-social-auth.php src/

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --level=5 wp-social-auth.php src/

      - name: Run PHP-CS-Fixer
        run: vendor/bin/php-cs-fixer fix wp-social-auth.php src/ --dry-run --diff --config=.php-cs-fixer.dist.php

  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    needs: lint
    permissions:
      contents: read
      actions: read
    strategy:
      matrix:
        php-version: ['7.4', '8.0', '8.1', '8.2']
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, xml, zip, intl, json, curl
          coverage: xdebug
          tools: composer:v2

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ matrix.php-version }}-
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run tests
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: wordpress-gmail-cli:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify scripts are executable
        run: |
          docker run --rm wordpress-gmail-cli:test sh -c "ls -la /app/bin/ | grep '\.sh'"
          docker run --rm wordpress-gmail-cli:test sh -c "test -x /app/bin/test-docker.sh && echo 'Script is executable' || echo 'Script is not executable'"