name: Lint and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Default permissions are read-only
permissions: read-all

jobs:
  lint-shell:
    name: Lint Shell Scripts
    runs-on: ubuntu-latest
    permissions:
      contents: read        # To checkout and read files
      pull-requests: write # OPTIONAL: To allow shfmt action to comment on PRs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@v2.0.0 # PINNED VERSION
        with:
          # Consider 'warning' or 'error' if 'style' is too noisy
          severity: style

      - name: Run shfmt for formatting check
        uses: luizm/action-sh-checker@v0.5.0
        env:
          SHFMT_OPTS: -i 2 -ci -bn # Indent 2, simplify case, binary ops follow
        with:
          # Set to false if PR comments are not needed or permission is not granted
          sh_checker_comment: true
          sh_checker_exclude: vendor # Exclude vendor directory

  lint-php:
    name: Lint PHP Files
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: phpcs, phpstan, php-cs-fixer

      - name: Run PHP_CodeSniffer
        # Adjust paths to your PHP source directories (e.g., src/ .)
        run: phpcs --standard=PSR12 src/ includes/ wp-social-auth.php

      - name: Run PHPStan
        # Adjust paths to your PHP source directories (e.g., src/ .)
        run: phpstan analyse src/ includes/ wp-social-auth.php --level=5

      - name: Run PHP-CS-Fixer (Dry Run)
        # Adjust paths to your PHP source directories (e.g., src/ .)
        run: php-cs-fixer fix src/ includes/ wp-social-auth.php --dry-run --diff

  # OPTIONAL: Add 'needs' if you want linting to finish before testing starts
  # needs: [lint-shell, lint-php]
  test-docker:
    name: Test Docker Build
    runs-on: ubuntu