name: Lint and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# Default permissions are read-only
permissions: read-all

jobs:
  lint-shell:
    name: Lint Shell Scripts
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run ShellCheck (informational only)
        uses: ludeeus/action-shellcheck@master
        with:
          severity: style
        continue-on-error: true
          
      - name: Run shfmt (informational only)
        uses: luizm/action-sh-checker@v0.5.0
        env:
          SHFMT_OPTS: -i 2 -ci -bn
        with:
          sh_checker_comment: true
          sh_checker_exclude: vendor
        continue-on-error: true
          
  lint-php:
    name: Lint PHP Files
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: phpcs, phpstan, php-cs-fixer
          
      - name: Run PHP_CodeSniffer (informational only)
        run: phpcs --standard=PSR12 wp-social-auth.php || true
        
      - name: Run PHPStan (informational only)
        run: phpstan analyse wp-social-auth.php --level=5 || true
        
      - name: Run PHP-CS-Fixer (informational only)
        run: php-cs-fixer fix wp-social-auth.php --dry-run --diff || true
        
  test-docker:
    name: Test Docker Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          load: true
          tags: wordpress-gmail-cli:test
          
      - name: Test Docker image
        run: |
          docker run --rm wordpress-gmail-cli:test --help || true
        continue-on-error: true
          
  test-scripts:
    name: Test Scripts
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Make scripts executable
        run: chmod +x bin/*.sh
        
      - name: Test version script
        run: bin/version.sh --version || true
        continue-on-error: true
        
      - name: Test enhance-ssl-security script
        run: bin/enhance-ssl-security.sh --version || true
        continue-on-error: true
