name: Lint and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint-shell:
    name: Lint Shell Scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: style
          
      - name: Run shfmt
        uses: luizm/action-sh-checker@v0.5.0
        env:
          SHFMT_OPTS: -i 2 -ci -bn
        with:
          sh_checker_comment: true
          sh_checker_exclude: "vendor"
          
  lint-php:
    name: Lint PHP Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: phpcs, phpstan, php-cs-fixer
          
      - name: Run PHP_CodeSniffer
        run: phpcs --standard=PSR12 wp-social-auth.php
        
      - name: Run PHPStan
        run: phpstan analyse wp-social-auth.php --level=5
        
      - name: Run PHP-CS-Fixer
        run: php-cs-fixer fix wp-social-auth.php --dry-run --diff
        
  test-docker:
    name: Test Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          load: true
          tags: wordpress-gmail-cli:test
          
      - name: Test Docker image
        run: |
          docker run --rm wordpress-gmail-cli:test --help
          
  test-scripts:
    name: Test Scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Make scripts executable
        run: chmod +x *.sh
        
      - name: Test version script
        run: ./version.sh --help
        
      - name: Test enhance-ssl-security script
        run: ./enhance-ssl-security.sh --help
