name: Release Workflow

on:
  push:
    tags:
      - 'v*' # Trigger only on tags like v1.0, v2.3.4

# Default permissions are read-only at workflow level
permissions: read-all

jobs:
  build-and-release:
    name: Build Docker Image and Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write   # To create the GitHub release & tag annotations
      packages: write  # To push Docker image to GHCR
      actions: write   # OPTIONAL: To write to GHA cache if caching is enabled below

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # fetch-depth: 0 # Uncomment if generate_release_notes has issues

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: version
        # Strips 'refs/tags/v' from the GITHUB_REF (e.g., refs/tags/v1.2.3 -> 1.2.3)
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            # Use owner/repo format for image name
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.version.outputs.version }}
          # OPTIONAL: Enable Docker layer caching for potentially faster builds
          # cache-from: type=gha
          # cache-to: type=gha,mode=max

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          # Use the tag name (e.g., v1.2.3) as the release name
          name: Release ${{ github.ref_name }}
          # Let the action generate release notes from commits since last release
          generate_release_notes: true
          # List of files to attach as release assets
          # !!! IMPORTANT: Verify these paths are correct relative to repo root !!!
          files: |
            bin/wordpress-gmail-cli.sh
            wp-social-auth.php
            bin/enhance-ssl-security.sh
            bin/get-gmail-credentials.sh