name: SLSA Provenance

on:
  workflow_dispatch:
  release:
    types: [created]

# Default permissions are read-only
permissions: read-all

jobs:
  build:
    name: Build and Generate Artifacts
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Build artifacts
        run: |
          mkdir -p dist
          cp *.sh dist/
          cp wp-social-auth.php dist/
          
      - name: Generate hashes
        id: hash
        run: |
          cd dist
          FILES=$(find . -type f | sort)
          echo "Hashing files: $FILES"
          
          # Generate sha256sum for each file
          for FILE in $FILES; do
            sha256sum "$FILE" >> ../sha256sums.txt
          done
          
          # Base64 encode the sha256sums file
          HASHES=$(cat ../sha256sums.txt | base64 -w0)
          echo "hashes=$HASHES" >> $GITHUB_OUTPUT
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wordpress-gmail-cli
          path: dist/
          
  provenance:
    name: Generate SLSA Provenance
    needs: [build]
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.6.0
    with:
      base64-subjects: ${{ needs.build.outputs.hashes }}
      upload-assets: true
